name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 1.0.0)'
        required: true
        type: string

permissions:
  # allow to push the release tag
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: git checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: install npm dependencies
        run: |
          nix develop --command \
          pnpm -r install --frozen-lockfile

      - name: Update packages version
        run: |
          nix develop --command \
            pnpm version-libs --version=${{ github.event.inputs.version }}

      - name: Dry-run publishing
        run: |
          nix develop --command \
            pnpm nx run-many -t publish --dry-run

      - name: Publish to npm
        run: |
          nix develop --command \
            pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_ACCESS_TOKEN }}
          nix develop --command \
            pnpm nx run-many -t publish

      - name: Tag
        run: |
          git tag ${TAG}
          git push origin ${TAG}
        env:
          TAG: v${{ github.event.inputs.version }}
